- hosts: all
  become: yes
  tasks: 
  - name: create users
    ansible.builtin.user:
      # name: johnd
      name: "{{ item }}"
      state: present
    # with_items:
    loop: 
      - tim
      - brad
      - ann
      - jenny